config/routes.rb
Rails.application.routes.draw do
  namespace :gamification do
    resources :levels
    resources :items
    resources :item_types
    resources :inventories
    resources :item_groups
  end
end

app/models/gamification.rb
module Gamification
    def self.table_name_prefix
      'gamification_'
    end
end

app/models/gamification/goal.rb
module Gamification
  class Goal < ApplicationRecord
    self.table_name = "gamification_goals"
    belongs_to :rewarding, polymorphic: true
    has_one :medal, dependent: :destroy
    has_many :rewards, dependent: :destroy

    accepts_nested_attributes_for :medal, allow_destroy: true, reject_if: :all_blank

    # TODO: These should be SQL. But that's hard.
    scope :completed_by,  ->(subject) { all.select { |goal| goal.completed_by? subject }}
    scope :incomplete_by, ->(subject) { all.reject { |goal| goal.completed_by? subject }}

    # Determine whether the given subject has completed the goal.
    #
    # subject - An ActiveRecord model that can receive rewards.
    def completed_by? subject
      !!reward_for(subject)
    end

    # Complete the goal for the given subject.
    #
    # subject - An ActiveRecord model that can receive rewards.
    def complete_for subject
      if completed_by? subject
        raise Completed, "#{self} is already completed for #{subject}"
      else
        Reward.create! goal: self, rewardable: subject
      end
    end

    private

    # Find the Reward for the given subject.
    #
    # subject - A rewardable model.
    def reward_for rewardable
      rewards.find_by rewardable: rewardable
    end
  end
end

app/models/gamification/inventory.rb
module Gamification
  class Inventory < ApplicationRecord
    self.table_name = "gamification_inventories"
    belongs_to :user
    belongs_to :item, class_name: 'Gamification::Item', foreign_key: :gamification_item_id

    scope :equipped, -> {where equipped: true}

    def unnequip_same_type_item(user_id)
      Inventory.where(user_id: user_id,gamification_items: {gamification_item_type_id: self.item.item_type.id}).joins(:item).update_all(equipped: false)
    end

    def unnequip_same_associated_jump_item(user_id)
      if self.item.item_type
        unequip_inventory = Inventory.where(user_id: user_id,gamification_item_types: {key: self.item.item_type.key + "jump"})
                                .joins(item: :item_group).joins(item: :item_type)
        if unequip_inventory.any?
          unequip_inventory.update_all(equipped: false)
        end
      end
    end

    def equipe_associated_jump_item(user_id)
      if self.item.item_group
        inventory = Inventory.where.not(id: self.id).where(user_id: user_id,gamification_item_groups: {id: self.item.item_group.id}).where(gamification_item_types: {key: self.item.item_type.key + "jump"})
                        .joins(item: :item_group).joins(item: :item_type)
        if inventory.any?
          inventory.update_all(:equipped => true)
        end
      end
    end

    def equip_item(user_id)
      unnequip_same_type_item(user_id)
      unnequip_same_associated_jump_item(user_id)
      equipe_associated_jump_item(user_id)
      self.update_attributes(:equipped => true)
    end

  end
end

app/models/gamification/item.rb
module Gamification
  class Item < ApplicationRecord
    self.table_name = "gamification_items"
    belongs_to :item_type,class_name: 'Gamification::ItemType',foreign_key: :gamification_item_type_id
    belongs_to :item_group,class_name: 'Gamification::ItemGroup',foreign_key: :gamification_item_group_id
    belongs_to :user
    has_many :inventories,class_name: 'Gamification::Inventory',foreign_key: :gamification_item_id

    has_one_attached :image
    end
end

app/models/gamification/item_group.rb
module Gamification
  class ItemGroup < ApplicationRecord
    self.table_name = "gamification_item_groups"
    has_many :items, class_name: 'Gamification::Item',
      foreign_key: :gamification_item_group_id
  end
end

app/models/gamification/item_type.rb
module Gamification
  class ItemType < ApplicationRecord
    self.table_name = "gamification_item_types"
    has_many :items,class_name: 'Gamification::Item',foreign_key: :gamification_item_type_id
  end
end

app/models/gamification/level.rb
module Gamification
  class Level < ApplicationRecord
    self.table_name = "gamification_levels"
  end
end

app/models/gamification/medal.rb
module Gamification
  class Medal < ApplicationRecord
    self.table_name = "gamification_medals"
    belongs_to :goal

    has_one_attached :image
  end
end

app/models/gamification/reward.rb
module Gamification
  class Reward < ApplicationRecord
    self.table_name = "gamification_rewards"
    belongs_to :goal
    belongs_to :rewardable, polymorphic: true, inverse_of: :rewards

    scope :unseen, -> { where seen_at: nil }
    scope :seen, -> { where.not seen_at: nil }

    scope :with_medals,    -> { all.select &:medal }
    scope :without_medals, -> { all.reject &:medal }

    validates :rewardable_id, uniqueness: { scope: [:rewardable_type, :goal] }

    delegate :points, to: :goal
    delegate :medal, to: :goal

    def see
      touch :seen_at
    end

    def seen?
      !!seen_at
    end

    class << self
      def see
        all.map { |reward| reward.see }
      end
    end
  end
end

app/controllers/gamification/inventories_controller.rb
class Gamification::InventoriesController < ApplicationController
  before_action :set_gamification_inventory, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:update]
  before_action :authenticate_user!
  load_and_authorize_resource except: [:create]

  # GET /gamification/inventories
  def index
    @gamification_inventories = Gamification::Inventory.all
  end

  # GET /gamification/inventories/1
  def show
  end

  # GET /gamification/inventories/new
  def new
    @gamification_inventory = Gamification::Inventory.new
  end

  # GET /gamification/inventories/1/edit
  def edit
  end

  # POST /gamification/inventories
  def create
    authorize! :create, @gamification_inventory

    @gamification_inventory = Gamification::Inventory.new(inventory_params)

    if @gamification_inventory.save
      redirect_to @gamification_inventory, notice: 'Inventory was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /gamification/inventories/1
  def update
    respond_to do |format|
      if @gamification_inventory.equip_item(params[:user_id].to_i)

        format.js
        format.json { head :no_content }
      else
        format.js
        format.json { render json: @gamification_inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gamification/inventories/1
  def destroy
    @gamification_inventory.destroy
    redirect_to gamification_inventories_url, notice: 'Inventory was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_gamification_inventory
    @gamification_inventory = Gamification::Inventory.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  # Only allow a trusted parameter "white list" through.

  def inventory_params
    params.require(:inventory).permit(:user_id, :equipped, :gamification_item_id)
  end
end

app/controllers/gamification/item_groups_controller.rb
class Gamification::ItemGroupsController < ApplicationController
  before_action :set_gamification_item_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource except: [:create]
  # GET /gamification/item_groups
  def index
    @gamification_item_groups = Gamification::ItemGroup.all
  end

  # GET /gamification/item_groups/1
  def show
  end

  # GET /gamification/item_groups/new
  def new
    @gamification_item_group = Gamification::ItemGroup.new
  end

  # GET /gamification/item_groups/1/edit
  def edit
  end

  # POST /gamification/item_groups
  def create
    authorize! :create, @gamification_item_group

    @gamification_item_group = Gamification::ItemGroup.new(gamification_item_group_params)

    if @gamification_item_group.save
      redirect_to @gamification_item_group, notice: 'Item group was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /gamification/item_groups/1
  def update
    if @gamification_item_group.update(gamification_item_group_params)
      redirect_to @gamification_item_group, notice: 'Item group was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /gamification/item_groups/1
  def destroy
    @gamification_item_group.destroy
    redirect_to gamification_item_groups_url, notice: 'Item group was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gamification_item_group
      @gamification_item_group = Gamification::ItemGroup.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def gamification_item_group_params
      params.require(:gamification_item_group).permit(:name)
    end
end

app/controllers/gamification/item_types_controller.rb
class Gamification::ItemTypesController < ApplicationController
  before_action :set_gamification_item_type, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource except: [:create]
  # GET /gamification/item_types
  def index
    @gamification_item_types = Gamification::ItemType.all
  end

  # GET /gamification/item_types/1
  def show
  end

  # GET /gamification/item_types/new
  def new
    @gamification_item_type = Gamification::ItemType.new
  end

  # GET /gamification/item_types/1/edit
  def edit
  end

  # POST /gamification/item_types
  def create
    authorize! :create, @gamification_item_type

    @gamification_item_type = Gamification::ItemType.new(gamification_item_type_params)

    if @gamification_item_type.save
      redirect_to @gamification_item_type, notice: 'Item type was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /gamification/item_types/1
  def update
    if @gamification_item_type.update(gamification_item_type_params)
      redirect_to @gamification_item_type, notice: 'Item type was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /gamification/item_types/1
  def destroy
    @gamification_item_type.destroy
    redirect_to gamification_item_types_url, notice: 'Item type was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gamification_item_type
      @gamification_item_type = Gamification::ItemType.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def gamification_item_type_params
      params.require(:gamification_item_type).permit(:name,:key)
    end
end

app/controllers/gamification/items_controller.rb
class Gamification::ItemsController < ApplicationController
  before_action :set_gamification_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource except: [:create]
  # GET /gamification/items
  def index
    @gamification_items = Gamification::Item.all
  end

  # GET /gamification/items/1
  def show
  end

  # GET /gamification/items/new
  def new
    @gamification_item = Gamification::Item.new
  end

  # GET /gamification/items/1/edit
  def edit
  end

  # POST /gamification/items
  def create
    authorize! :create, @gamification_item

    @gamification_item = Gamification::Item.new(gamification_item_params)

    if @gamification_item.save
      redirect_to @gamification_item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /gamification/items/1
  def update
    if @gamification_item.update(gamification_item_params)
      redirect_to @gamification_item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /gamification/items/1
  def destroy
    @gamification_item.destroy
    redirect_to gamification_items_url, notice: 'Item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gamification_item
      @gamification_item = Gamification::Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def gamification_item_params
      params.require(:gamification_item).permit(:name, :gamification_item_type_id,:gamification_item_group_id, :image, :rarity, :cost,:user_id, :description)
    end
end

app/controllers/gamification/levels_controller.rb
module Gamification
  class LevelsController < ApplicationController
    before_action :authenticate_user!, except: [:list, :show_list]
    before_action :authenticate_user!
    load_and_authorize_resource except: [:create]

    # GET /levels
    def index
      @levels = Level.all
    end

    # GET /levels/1
    def show
    end

    # GET /levels/new
    def new
      @level = Level.new
    end

    # GET /levels/1/edit
    def edit
    end

    # POST /levels
    def create
      authorize! :create, @level

      @level = Level.new(level_params)

      if @level.save
        redirect_to @level, notice: 'Level was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /levels/1
    def update
      if @level.update(level_params)
        redirect_to @level, notice: 'Level was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /levels/1
    def destroy
      @level.destroy
      redirect_to levels_url, notice: 'Level was successfully destroyed.'
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def level_params
      params.fetch(:level, {})
    end

  end
end

app/controllers/gamification/rewards_controller.rb
module Gamification
  class RewardsController < ApplicationController
    before_action :verify_checksum
    before_action :authenticate_user!
    load_and_authorize_resource except: [:create]

    def create
      if rewarding.is_a? ::Gamification::Goal
        rewarding.complete_for rewardable
      else
        rewarding.goals.each do |goal|
          goal.complete_for rewardable
        end
      end

      respond_to do |format|
        format.json { render json: {}, status: :created }
        format.html { redirect_to redirect_url }
      end
    end

    private

    def verify_checksum
      render text: "Invalid checksum", status: :forbidden unless Checksum.verify(params[:checksum],
                                                                                 [rewarding.class.name, rewarding.id, rewardable.class.name, rewardable.id])
    end

    def redirect_url
      params[:redirect_url] || request.env['HTTP_REFERER']
    end

    def rewarding
      rewarding_model.find reward_params[:rewarding_id]
    end

    def rewardable
      rewardable_model.find reward_params[:rewardable_id]
    end

    def rewarding_model
      reward_params[:rewarding_type].constantize
    end

    def rewardable_model
      reward_params[:rewardable_type].constantize
    end

    def reward_params
      params.require(:reward).permit(:rewarding_type, :rewarding_id, :rewardable_type, :rewardable_id)
    end
  end
end

app/helpers/gamification/application_helper.rb
module Gamification
  module ApplicationHelper


    # Create a form to reward someone for something.
    #
    # rewardable - A model that is rewardable (e.g. a user)
    # options    - A Hash of options:
    #              :for      - A model that is rewarding (e.g. an article)
    #              :redirect - A String describing a URL to redirect to.
    def reward rewardable, options
      rewarding = options[:for]
      redirect  = options[:redirect]

      form_tag Gamification::Engine.routes.url_helpers.rewards_path, method: :post do
        concat hidden_field_tag 'reward[rewarding_type]', rewarding.class.name
        concat hidden_field_tag 'reward[rewarding_id]', rewarding.id
        concat hidden_field_tag 'reward[rewardable_type]', rewardable.class.name
        concat hidden_field_tag 'reward[rewardable_id]', rewardable.id
        concat hidden_field_tag 'checksum', Checksum.generate(
          [rewarding.class.name, rewarding.id, rewardable.class.name, rewardable.id]
        )

        if redirect
          concat hidden_field_tag 'redirect_url', redirect
        end

        concat submit_tag I18n.t 'go_gamification.complete'
      end
    end
  end
end

app/helpers/gamification/inventories_helper.rb
module Gamification::InventoriesHelper
end

app/helpers/gamification/item_groups_helper.rb
module Gamification::ItemGroupsHelper
end

app/helpers/gamification/item_types_helper.rb
module Gamification::ItemTypesHelper
end

app/helpers/gamification/items_helper.rb
module Gamification::ItemsHelper
end

app/views/gamification/inventories/_form.html.erb
<%= form_with(model: gamification_inventory, local: true) do |form| %>
  <% if gamification_inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gamification_inventory.errors.count, "error") %> prohibited this gamification_inventory from being saved:</h2>

      <ul>
      <% gamification_inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :User_id %>
    <%= form.text_field :User_id, id: :gamification_inventory_User_id %>
  </div>

  <div class="field">
    <%= form.label :Item_id %>
    <%= form.text_field :Item_id, id: :gamification_inventory_Item_id %>
  </div>

  <div class="field">
    <%= form.label :equipped %>
    <%= form.check_box :equipped, id: :gamification_inventory_equipped %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gamification/inventories/_inventory.html.erb
<div id="inventory">
  <div class="col-lg-8">
    <div class="row">

      <% Gamification::ItemType.where("gamification_item_types.key not in('legsjump','rightarmjump','leftarmjump')").select(:key).distinct.order(key: :asc).each do |item_type| %>
        <% Gamification::Inventory.where(user_id: current_user.id, gamification_item_types: { key: item_type.key })
               .joins(item: :item_type).each do |inventory| %>
          <div class="col-lg-2">
            <div class="ibox-content" >
            <div class="block-content block-content-full bg-gray-lighter border-black-op" style="min-height: 75px;max-height:
                50px" data-toggle="popover" title="" data-placement="top" data-content="<%= inventory.item.description %>" type="button" data-original-title="<%= inventory.item.name %>">
              <div class="h5 font-w700"><%= image_tag inventory.item.image.variant(resize: "#{50}x#{nil}").processed unless Rails.env.development? %></div>

            </div>
            <% if inventory.equipped %>
                <button class="btn btn-xs btn-info push-5-r push-10" type="button"><i class="fa fa-check-square ">Equipado</i></button>
            <% else %>
              <%= link_to gamification_inventory_path(inventory, gamification_item_id: inventory.gamification_item_id,
                                                      user_id: current_user.id, :equipped => true), :remote => true,
                          :method => :put, class: 'btn btn-success btn-xs', :data => { :disable_with => "<i class='fa fa-cogs' aria-hidden='true'></i>Equipando".html_safe } do %>
                Equipar
              <% end %>
            <% end %>
          </div>
          </div>
        <% end %>
      <% end %>
    </div>

  </div>
</div>

app/views/gamification/inventories/edit.html.erb
<h1>Editing Gamification Inventory</h1>

<%= render 'form', gamification_inventory: @gamification_inventory %>

<%= link_to 'Show', @gamification_inventory %> |
<%= link_to 'Back', gamification_inventories_path %>

app/views/gamification/inventories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gamification Inventories</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Item</th>
      <th>Equipped</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gamification_inventories.each do |gamification_inventory| %>
      <tr>
        <td><%= gamification_inventory.User %></td>
        <td><%= gamification_inventory.Item %></td>
        <td><%= gamification_inventory.equipped %></td>
        <td><%= link_to 'Show', gamification_inventory %></td>
        <td><%= link_to 'Edit', edit_gamification_inventory_path(gamification_inventory) %></td>
        <td><%= link_to 'Destroy', gamification_inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gamification Inventory', new_gamification_inventory_path %>

app/views/gamification/inventories/new.html.erb
<h1>New Gamification Inventory</h1>

<%= render 'form', gamification_inventory: @gamification_inventory %>

<%= link_to 'Back', gamification_inventories_path %>

app/views/gamification/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @gamification_inventory.User %>
</p>

<p>
  <strong>Item:</strong>
  <%= @gamification_inventory.Item %>
</p>

<p>
  <strong>Equipped:</strong>
  <%= @gamification_inventory.equipped %>
</p>

<%= link_to 'Edit', edit_gamification_inventory_path(@gamification_inventory) %> |
<%= link_to 'Back', gamification_inventories_path %>

app/views/gamification/inventories/update.js.erb
$('#inventory').html('<%= escape_javascript render 'inventory' %>');

var parts = [
    {
        name: 'leftArm',
        ident: "<%= @user.decorate.equipped_left_arm%>",
        visible: true,
        x: charX + 40,
        y: charY - 42 - breathAmt
    },
    {
        name: 'leftArmjump',
        ident: "<%= @user.decorate.equipped_left_arm_jump %>",
        visible: false,
        x: charX + 40,
        y: charY - 42 - breathAmt
    },
    {name: 'legs', ident: "<%= @user.decorate.equipped_legs %>", visible: true, x: charX, y: charY},
    {
        name: 'legsjump',
        ident: "<%= @user.decorate.equipped_legs_jump%>",
        visible: false,
        x: charX,
        y: charY - 6
    },
    {name: 'torso', ident: "<%= @user.decorate.equipped_torso %>", visible: true, x: charX, y: charY - 50},
    {
        name: 'head',
        ident: "<%= @user.decorate.equipped_head %>",
        visible: true,
        x: charX - 10,
        y: charY - 125 - breathAmt
    },
    {
        name: 'hair',
        ident: "<%= @user.decorate.equipped_hair %>",
        visible: true,
        x: charX - 37,
        y: charY - 138 - breathAmt
    },
    {
        name: 'rightArm',
        ident: "<%= @user.decorate.equipped_right_arm %>",
        visible: true,
        x: charX - 15,
        y: charY - 42 - breathAmt
    },
    {
        name: 'rightArmjump',
        ident: "<%= @user.decorate.equipped_right_arm_jump %>",
        visible: false,
        x: charX - 35,
        y: charY - 42 - breathAmt
    },

];
var bodyParts = [];

var num_of_imgs = parts.length + 2;
var loaded_imgs = 0;

function myLoop() {
    bg.draw();

    //update the cloud
    cx = cloud.x - cloudSpeed;

    if (cx + cloud.width < 0) {
        cx = engine._stageWidth + 20;
        cy = Math.floor(Math.random() * 50);
        cloud.y = cy;
    }

    cloud.x = cx;
    cloud.draw();

    x = charX;
    y = charY;

    if (isJumping) {
        y -= jumpHeight;
    }

    character.y = y;
    // Update parts for breathing
    bodyParts.head.y = charY - 125 - breathAmt;
    bodyParts.hair.y = charY - 138 - breathAmt;

    if (isJumping) {
        bodyParts.leftArmjump.visible = true;
        bodyParts.rightArmjump.visible = true;
        bodyParts.legsjump.visible = true;

        bodyParts.leftArm.visible = false;
        bodyParts.rightArm.visible = false;
        bodyParts.legs.visible = false;
    } else {
        bodyParts.leftArmjump.visible = false;
        bodyParts.rightArmjump.visible = false;
        bodyParts.legsjump.visible = false;

        bodyParts.leftArm.visible = true;
        bodyParts.rightArm.visible = true;
        bodyParts.legs.visible = true;

        bodyParts.leftArm.y = charY - 42 - breathAmt;
        bodyParts.rightArm.y = charY - 42 - breathAmt;
    }

    bodyParts.leftEye.y = charY - 68 - breathAmt;
    bodyParts.rightEye.y = charY - 68 - breathAmt;

    eyeOpenTime += blinkUpdateTime;

    if (eyeOpenTime >= timeBtwBlinks) {
        blink();
    }

    bodyParts.leftEye.height = curEyeHeight;
    bodyParts.rightEye.height = curEyeHeight;

    character.draw();
    fps_text.text = "Current FPS: " + engine.getFPS();
    fps_text.draw();
    updateBreath();
}

$(document).ready(function () {


    character = engine.createClip({
        x: charX,
        y: charY
    });

    for (part in parts) {
        o = parts[part];
        bodyParts[o.name] = engine.createBitmap({
            src: o.ident,
            x: o.x,
            y: o.y,
            visible: o.visible
        });

        bodyParts[o.name].addEventListener('onload', increaseLoaded);
        character.add(bodyParts[o.name]);
    }

    bodyParts['leftEye'] = engine.createShape({
        shape: 'elipse',
        style: 'filled',
        x: charX + 47,
        y: charY - 68 - breathAmt,
        width: 8,
        height: curEyeHeight,
    });

    bodyParts['rightEye'] = engine.createShape({
        shape: 'elipse',
        style: 'filled',
        x: charX + 58,
        y: charY - 68 - breathAmt,
        width: 8,
        height: curEyeHeight
    });

    character.add(bodyParts['leftEye']);
    character.add(bodyParts['rightEye']);

    bg = engine.createBitmap({
        src: "<%= @user.decorate.equipped_background %>",
        x: 0,
        y: 0
    });

    bg.addEventListener('onload', increaseLoaded);

    cloud = engine.createBitmap({
        src: "<%=@user.decorate.equipped_flyingobject %>",
        x: engine._stageWidth + 20,
        y: 80
    });

    cloud.addEventListener('onload', increaseLoaded);

    fps_text = engine.createText({
        text: "FPS",
        color: 'rgba(255,255,255,1)',
        x: 20,
        y: 20
    });

});