config/routes.rb
Rails.application.routes.draw do
  namespace :gamification do
    resources :levels
    resources :items
    resources :item_types
    resources :inventories
    resources :item_groups
  end
end

app/models/gamification.rb
module Gamification
    def self.table_name_prefix
      'gamification_'
    end
end

app/models/gamification/goal.rb
module Gamification
  class Goal < ApplicationRecord
    self.table_name = "gamification_goals"
    belongs_to :rewarding, polymorphic: true
    has_one :medal, dependent: :destroy
    has_many :rewards, dependent: :destroy

    accepts_nested_attributes_for :medal, allow_destroy: true, reject_if: :all_blank

    # TODO: These should be SQL. But that's hard.
    scope :completed_by,  ->(subject) { all.select { |goal| goal.completed_by? subject }}
    scope :incomplete_by, ->(subject) { all.reject { |goal| goal.completed_by? subject }}

    # Determine whether the given subject has completed the goal.
    #
    # subject - An ActiveRecord model that can receive rewards.
    def completed_by? subject
      !!reward_for(subject)
    end

    # Complete the goal for the given subject.
    #
    # subject - An ActiveRecord model that can receive rewards.
    def complete_for subject
      if completed_by? subject
        raise Completed, "#{self} is already completed for #{subject}"
      else
        Reward.create! goal: self, rewardable: subject
      end
    end

    private

    # Find the Reward for the given subject.
    #
    # subject - A rewardable model.
    def reward_for rewardable
      rewards.find_by rewardable: rewardable
    end
  end
end

app/models/gamification/inventory.rb
module Gamification
  class Inventory < ApplicationRecord
    self.table_name = "gamification_inventories"
    belongs_to :user
    belongs_to :item, class_name: 'Gamification::Item', foreign_key: :gamification_item_id

    scope :equipped, -> {where equipped: true}

    def unnequip_same_type_item(user_id)
      Inventory.where(user_id: user_id,gamification_items: {gamification_item_type_id: self.item.item_type.id}).joins(:item).update_all(equipped: false)
    end

    def unnequip_same_associated_jump_item(user_id)
      if self.item.item_type
        unequip_inventory = Inventory.where(user_id: user_id,gamification_item_types: {key: self.item.item_type.key + "jump"})
                                .joins(item: :item_group).joins(item: :item_type)
        if unequip_inventory.any?
          unequip_inventory.update_all(equipped: false)
        end
      end
    end

    def equipe_associated_jump_item(user_id)
      if self.item.item_group
        inventory = Inventory.where.not(id: self.id).where(user_id: user_id,gamification_item_groups: {id: self.item.item_group.id}).where(gamification_item_types: {key: self.item.item_type.key + "jump"})
                        .joins(item: :item_group).joins(item: :item_type)
        if inventory.any?
          inventory.update_all(:equipped => true)
        end
      end
    end

    def equip_item(user_id)
      unnequip_same_type_item(user_id)
      unnequip_same_associated_jump_item(user_id)
      equipe_associated_jump_item(user_id)
      self.update_attributes(:equipped => true)
    end

  end
end

app/models/gamification/item.rb
module Gamification
  class Item < ApplicationRecord
    self.table_name = "gamification_items"
    belongs_to :item_type,class_name: 'Gamification::ItemType',foreign_key: :gamification_item_type_id
    belongs_to :item_group,class_name: 'Gamification::ItemGroup',foreign_key: :gamification_item_group_id
    belongs_to :user
    has_many :inventories,class_name: 'Gamification::Inventory',foreign_key: :gamification_item_id

    has_one_attached :image
    end
end

app/models/gamification/item_group.rb
module Gamification
  class ItemGroup < ApplicationRecord
    self.table_name = "gamification_item_groups"
    has_many :items, class_name: 'Gamification::Item',
      foreign_key: :gamification_item_group_id
  end
end

app/models/gamification/item_type.rb
module Gamification
  class ItemType < ApplicationRecord
    self.table_name = "gamification_item_types"
    has_many :items,class_name: 'Gamification::Item',foreign_key: :gamification_item_type_id
  end
end

app/models/gamification/level.rb
module Gamification
  class Level < ApplicationRecord
    self.table_name = "gamification_levels"
  end
end

app/models/gamification/medal.rb
module Gamification
  class Medal < ApplicationRecord
    self.table_name = "gamification_medals"
    belongs_to :goal

    has_one_attached :image
  end
end

app/models/gamification/reward.rb
module Gamification
  class Reward < ApplicationRecord
    self.table_name = "gamification_rewards"
    belongs_to :goal
    belongs_to :rewardable, polymorphic: true, inverse_of: :rewards

    scope :unseen, -> { where seen_at: nil }
    scope :seen, -> { where.not seen_at: nil }

    scope :with_medals,    -> { all.select &:medal }
    scope :without_medals, -> { all.reject &:medal }

    validates :rewardable_id, uniqueness: { scope: [:rewardable_type, :goal] }

    delegate :points, to: :goal
    delegate :medal, to: :goal

    def see
      touch :seen_at
    end

    def seen?
      !!seen_at
    end

    class << self
      def see
        all.map { |reward| reward.see }
      end
    end
  end
end

app/controllers/gamification/inventories_controller.rb
class Gamification::InventoriesController < ApplicationController
  before_action :set_gamification_inventory, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:update]
  before_action :authenticate_user!
  load_and_authorize_resource except: [:create]

  # GET /gamification/inventories
  def index
    @gamification_inventories = Gamification::Inventory.all
  end

  # GET /gamification/inventories/1
  def show
  end

  # GET /gamification/inventories/new
  def new
    @gamification_inventory = Gamification::Inventory.new
  end

  # GET /gamification/inventories/1/edit
  def edit
  end

  # POST /gamification/inventories
  def create
    authorize! :create, @gamification_inventory

    @gamification_inventory = Gamification::Inventory.new(inventory_params)

    if @gamification_inventory.save
      redirect_to @gamification_inventory, notice: 'Inventory was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /gamification/inventories/1
  def update
    respond_to do |format|
      if @gamification_inventory.equip_item(params[:user_id].to_i)

        format.js
        format.json { head :no_content }
      else
        format.js
        format.json { render json: @gamification_inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gamification/inventories/1
  def destroy
    @gamification_inventory.destroy
    redirect_to gamification_inventories_url, notice: 'Inventory was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_gamification_inventory
    @gamification_inventory = Gamification::Inventory.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  # Only allow a trusted parameter "white list" through.

  def inventory_params
    params.require(:inventory).permit(:user_id, :equipped, :gamification_item_id)
  end
end

app/controllers/gamification/item_groups_controller.rb
class Gamification::ItemGroupsController < ApplicationController
  before_action :set_gamification_item_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource except: [:create]
  # GET /gamification/item_groups
  def index
    @gamification_item_groups = Gamification::ItemGroup.all
  end

  # GET /gamification/item_groups/1
  def show
  end

  # GET /gamification/item_groups/new
  def new
    @gamification_item_group = Gamification::ItemGroup.new
  end

  # GET /gamification/item_groups/1/edit
  def edit
  end

  # POST /gamification/item_groups
  def create
    authorize! :create, @gamification_item_group

    @gamification_item_group = Gamification::ItemGroup.new(gamification_item_group_params)

    if @gamification_item_group.save
      redirect_to @gamification_item_group, notice: 'Item group was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /gamification/item_groups/1
  def update
    if @gamification_item_group.update(gamification_item_group_params)
      redirect_to @gamification_item_group, notice: 'Item group was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /gamification/item_groups/1
  def destroy
    @gamification_item_group.destroy
    redirect_to gamification_item_groups_url, notice: 'Item group was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gamification_item_group
      @gamification_item_group = Gamification::ItemGroup.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def gamification_item_group_params
      params.require(:gamification_item_group).permit(:name)
    end
end

app/controllers/gamification/item_types_controller.rb
class Gamification::ItemTypesController < ApplicationController
  before_action :set_gamification_item_type, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource except: [:create]
  # GET /gamification/item_types
  def index
    @gamification_item_types = Gamification::ItemType.all
  end

  # GET /gamification/item_types/1
  def show
  end

  # GET /gamification/item_types/new
  def new
    @gamification_item_type = Gamification::ItemType.new
  end

  # GET /gamification/item_types/1/edit
  def edit
  end

  # POST /gamification/item_types
  def create
    authorize! :create, @gamification_item_type

    @gamification_item_type = Gamification::ItemType.new(gamification_item_type_params)

    if @gamification_item_type.save
      redirect_to @gamification_item_type, notice: 'Item type was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /gamification/item_types/1
  def update
    if @gamification_item_type.update(gamification_item_type_params)
      redirect_to @gamification_item_type, notice: 'Item type was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /gamification/item_types/1
  def destroy
    @gamification_item_type.destroy
    redirect_to gamification_item_types_url, notice: 'Item type was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gamification_item_type
      @gamification_item_type = Gamification::ItemType.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def gamification_item_type_params
      params.require(:gamification_item_type).permit(:name,:key)
    end
end

app/controllers/gamification/items_controller.rb
class Gamification::ItemsController < ApplicationController
  before_action :set_gamification_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource except: [:create]
  # GET /gamification/items
  def index
    @gamification_items = Gamification::Item.all
  end

  # GET /gamification/items/1
  def show
  end

  # GET /gamification/items/new
  def new
    @gamification_item = Gamification::Item.new
  end

  # GET /gamification/items/1/edit
  def edit
  end

  # POST /gamification/items
  def create
    authorize! :create, @gamification_item

    @gamification_item = Gamification::Item.new(gamification_item_params)

    if @gamification_item.save
      redirect_to @gamification_item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /gamification/items/1
  def update
    if @gamification_item.update(gamification_item_params)
      redirect_to @gamification_item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /gamification/items/1
  def destroy
    @gamification_item.destroy
    redirect_to gamification_items_url, notice: 'Item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gamification_item
      @gamification_item = Gamification::Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def gamification_item_params
      params.require(:gamification_item).permit(:name, :gamification_item_type_id,:gamification_item_group_id, :image, :rarity, :cost,:user_id, :description)
    end
end

app/controllers/gamification/levels_controller.rb
module Gamification
  class LevelsController < ApplicationController
    before_action :authenticate_user!, except: [:list, :show_list]
    before_action :authenticate_user!
    load_and_authorize_resource except: [:create]

    # GET /levels
    def index
      @levels = Level.all
    end

    # GET /levels/1
    def show
    end

    # GET /levels/new
    def new
      @level = Level.new
    end

    # GET /levels/1/edit
    def edit
    end

    # POST /levels
    def create
      authorize! :create, @level

      @level = Level.new(level_params)

      if @level.save
        redirect_to @level, notice: 'Level was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /levels/1
    def update
      if @level.update(level_params)
        redirect_to @level, notice: 'Level was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /levels/1
    def destroy
      @level.destroy
      redirect_to levels_url, notice: 'Level was successfully destroyed.'
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def level_params
      params.fetch(:level, {})
    end

  end
end

app/controllers/gamification/rewards_controller.rb
module Gamification
  class RewardsController < ApplicationController
    before_action :verify_checksum
    before_action :authenticate_user!
    load_and_authorize_resource except: [:create]

    def create
      if rewarding.is_a? ::Gamification::Goal
        rewarding.complete_for rewardable
      else
        rewarding.goals.each do |goal|
          goal.complete_for rewardable
        end
      end

      respond_to do |format|
        format.json { render json: {}, status: :created }
        format.html { redirect_to redirect_url }
      end
    end

    private

    def verify_checksum
      render text: "Invalid checksum", status: :forbidden unless Checksum.verify(params[:checksum],
                                                                                 [rewarding.class.name, rewarding.id, rewardable.class.name, rewardable.id])
    end

    def redirect_url
      params[:redirect_url] || request.env['HTTP_REFERER']
    end

    def rewarding
      rewarding_model.find reward_params[:rewarding_id]
    end

    def rewardable
      rewardable_model.find reward_params[:rewardable_id]
    end

    def rewarding_model
      reward_params[:rewarding_type].constantize
    end

    def rewardable_model
      reward_params[:rewardable_type].constantize
    end

    def reward_params
      params.require(:reward).permit(:rewarding_type, :rewarding_id, :rewardable_type, :rewardable_id)
    end
  end
end

app/helpers/gamification/application_helper.rb
module Gamification
  module ApplicationHelper


    # Create a form to reward someone for something.
    #
    # rewardable - A model that is rewardable (e.g. a user)
    # options    - A Hash of options:
    #              :for      - A model that is rewarding (e.g. an article)
    #              :redirect - A String describing a URL to redirect to.
    def reward rewardable, options
      rewarding = options[:for]
      redirect  = options[:redirect]

      form_tag Gamification::Engine.routes.url_helpers.rewards_path, method: :post do
        concat hidden_field_tag 'reward[rewarding_type]', rewarding.class.name
        concat hidden_field_tag 'reward[rewarding_id]', rewarding.id
        concat hidden_field_tag 'reward[rewardable_type]', rewardable.class.name
        concat hidden_field_tag 'reward[rewardable_id]', rewardable.id
        concat hidden_field_tag 'checksum', Checksum.generate(
          [rewarding.class.name, rewarding.id, rewardable.class.name, rewardable.id]
        )

        if redirect
          concat hidden_field_tag 'redirect_url', redirect
        end

        concat submit_tag I18n.t 'go_gamification.complete'
      end
    end
  end
end

app/helpers/gamification/inventories_helper.rb
module Gamification::InventoriesHelper
end

app/helpers/gamification/item_groups_helper.rb
module Gamification::ItemGroupsHelper
end

app/helpers/gamification/item_types_helper.rb
module Gamification::ItemTypesHelper
end

app/helpers/gamification/items_helper.rb
module Gamification::ItemsHelper
end

app/views/gamification/items/_collection.html.erb
<% collection.each do |resource| %>
    <tr id="<%= dom_id(resource) %>">
      <td><%= resource.name %></td>
      <td><%= resource.item_type.name %></td>
      <td> <%=  image_tag url_for(resource.image) if resource.image.attached?%></td>
      <td><%= resource.rarity %></td>
      <td><%= resource.cost %></td>
      <td><%= resource.user.realname %></td>
      <td><%= resource.description %></td>
      <td class="text-center">
            <%= link_to 'Show',  resource %>
            <%= link_to 'Edit', edit_gamification_item_path(resource) %>
            <%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
      </td>
    </tr>
<% end %>

app/views/gamification/items/_form.html.erb
<%= simple_form_for(@gamification_item) do |f| %>
    <%= f.error_notification %>

    <div class="field">
      <%= f.input :name, id: :gamification_item_name %>
      <%= f.input :description, id: :gamification_item_description %>
      <%= f.input :gamification_item_type_id,:collection => Gamification::ItemType.all,:value_method => :id,:label => "Tipo" ,:include_blank => false %>
      <%= f.input :gamification_item_group_id,:collection => Gamification::ItemGroup.all,:value_method => :id,:label => "Grupo" ,:include_blank => false %>

      <%= f.select :rarity, [['Comum', 1], ['Raro', 2], ['Super Raro', 3], ['Ultra Raro', 4], ['Secreto Raro', 5], ['Ultimate Raro', 6]] %>

      <%= f.input :cost, id: :gamification_item_cost %>

      <%= f.input :user_id,:collection => User.staff,label_method: :realname,:value_method => :id,:label => "User" ,:include_blank =>
          false %>

      <%= f.file_field :image %>

      <%= f.submit %>
    </div>
<% end %>

app/views/gamification/items/_pagination.html.erb
<div class="paging_simple_numbers">
  <%= paginate collection, remote: true  %>
</div>

app/views/gamification/items/edit.html.erb
<h1>Editing Gamification Item</h1>

<%= render 'form', gamification_item: @gamification_item %>

<%= link_to 'Show', @gamification_item %> |
<%= link_to 'Back', gamification_items_path %>

app/views/gamification/items/index.html.erb
<%= provide :page_title, I18n.t('links.index.header') %>
<%= provide :breadcrumb do %>
    <li><%= I18n.t('activerecord.models.link.other') %></li>
<% end %>

<main id="main-container" style="min-height: 530px;">
  <div class="content bg-gray-lighter">
    <div class="row items-push">
      <div class="col-sm-7">
        <h1 class="page-heading">
          <%= t('links.index.title') %>
        </h1>
      </div>
    </div>
  </div>
  <div class="content">
    <div class="block">
      <div class="block-header text-right">
        <h3 class="block-title">
        </h3>
        <span >
          <%= link_to I18n.t('links.new.header'), new_gamification_item_path, class: 'btn btn-sm btn-square btn-success' %>
        </span>
      </div>
      <div class="block-content">
        <table class="table table-striped">
          <thead>
          <tr>
            <th><%=t 'activerecord.attributes.link.name' %></th>
            <th class="text-center" style="width: 150px;"><%=t 'misc.actions' %></th>
          </tr>
          </thead>
          <tbody id='link_categories'>
          <%= render 'collection', collection: @gamification_items %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/gamification/items/new.html.erb
<%= provide :page_title, I18n.t('links.new.header') %>
<%= provide :breadcrumb do %>
    <li><%= link_to  t('activerecord.models.link.other'), gamification_items_path %></li>
    <li><%=t 'links.new.header' %></li>
<% end %>

<main id="main-container" style="min-height: 530px;">
  <div class="content bg-gray-lighter">
    <div class="row items-push">
      <div class="col-sm-7">
        <h1 class="page-heading">
          <%= I18n.t('links.new.title') %>
        </h1>
      </div>
    </div>
  </div>
  <div class="content">
    <div class="block">
      <div class="block-content">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</main>

app/views/gamification/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gamification_item.name %>
</p>

<p>
  <strong>Itemtype:</strong>
  <%= @gamification_item.item_type %>
</p>

<p>
  <strong>Image:</strong>
  <%= @gamification_item.image %>
 <%=  image_tag @gamification_item.image%>
</p>

<p>
  <strong>Rarity:</strong>
  <%= @gamification_item.rarity %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @gamification_item.cost %>
</p>

<p>
  <strong>User:</strong>
  <%= @gamification_item.user_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @gamification_item.description %>
</p>

<%= link_to 'Edit', edit_gamification_item_path(@gamification_item) %> |
<%= link_to 'Back', gamification_items_path %>